#!/bin/bash

# Script for managing sip-users for asterisk in mysql

userdb=asteriskuser
passdb=asteriskpassword
database=asteriskdatabase
hostdb=host
tabledb=sipuserstable
mysqlconnect="mysql -h $hostdb -u $userdb -p$passdb -D $database"
txtred='\033[0;31m'
txtyellow='\033[0;33m'
txtnormal='\033[0m'
onlynumbers='^[0-9]+$'
defaultcontext=default

# showing menu
PS3="Please enter an action: "
options=("Quit" "Add" "Del" "Show" "Edit")
select actitem in "${options[@]}"
do
case $actitem in
    Quit)
	echo Bye!
	break
	;;
    Add)
	echo -n "Callnumber: "
	while read sipdefaultuser ; do
		# check that input data is a digital
		# check that sipdefaultuser exists
		checkdefaultuser=`$mysqlconnect -B -N -e "select defaultuser from $tabledb where defaultuser = '$sipdefaultuser';"`
		if [ "$checkdefaultuser" == "$sipdefaultuser" ]; then
			echo -en "$txtred""Callnumber $txtyellow$sipdefaultuser$txtred already exists, please enter another: ""$txtnormal"
		else
			# check that input data is a digital
			if [[ $sipdefaultuser =~ $onlynumbers ]] ; then
				[ "4" -eq `echo -n $sipdefaultuser | wc -m` ] && break || echo -en "$txtred""Callnumber must have 4 digitals only, please enter another: ""$txtnormal"
			else
				echo -en "$txtred""Callnumber must be numeric only, please enter another: ""$txtnormal"
			fi
		fi
	done
	echo -n "Group(context)[$defaultcontext]: "
	read sipcontext
	[ -z "$sipcontext" ] && sipcontext="$defaultcontext"
	echo -n "Name: "
	while read sipname ; do
		# check that sipname exists
		checkname=`$mysqlconnect -B -N -e "select name from $tabledb where name = $sipname;"`
		if [ "$checkname" == "$sipname" ]; then
			echo -en "$txtred""Name $txtyellow$sipname$txtred already exists, please enter another: ""$txtnormal"
		else
			break
		fi
	done
	echo -n "Password: "
	read sipsecret
	# write users items to db
	$mysqlconnect -e "INSERT INTO $tabledb (context,defaultuser,secret,name) VALUES ('$sipcontext','$sipdefaultuser','$sipsecret','$sipname');"
	echo "Done."
        ;;
    Del)
	echo -n "Callnumber to delete: "
	while read sipdefaultuser ; do
		# check that sipdefaultuser exists
		checkdefaultuser=`$mysqlconnect -B -N -e "select defaultuser from $tabledb where defaultuser = $sipdefaultuser;"`
		if [ "$checkdefaultuser" == "$sipdefaultuser" ]; then
			break
		else
			echo -en "$txtred""Callnumber $txtyellow$sipdefaultuser$txtred not exists, please enter another: ""$txtnormal"
		fi
	done
	$mysqlconnect -e "DELETE FROM $tabledb WHERE defaultuser = $sipdefaultuser;"
	echo "Done."
        ;;
    Show)
	$mysqlconnect -e "SELECT defaultuser,secret,context,name FROM $tabledb;"
	;;
    Edit)
	echo -n "Callnumber to edit: "
	# check that sipdefaultuser exists
	while read sipdefaultuser ; do
		checkdefaultuser=`$mysqlconnect -B -N -e "SELECT defaultuser FROM $tabledb WHERE defaultuser = '$sipdefaultuser';"`
		if [ "$checkdefaultuser" == "$sipdefaultuser" ]; then
			# check that input data is a digital
			break
		else
			echo -en "$txtred""Callnumber $txtyellow$sipdefaultuser$txtred not exists, please enter another: ""$txtnormal"
		fi
	done
	# old defaultuser as default
	olddefaultuser=`$mysqlconnect -B -N -e "SELECT defaultuser FROM $tabledb WHERE defaultuser = '$sipdefaultuser';"`
	echo -n "New callnumber[$olddefaultuser]: "
	while read newdefaultuser ; do
	[ -z "$newdefaultuser" ] && break
	# check that sipdefaultuser exists
		checkdefaultuser=`$mysqlconnect -B -N -e "select defaultuser from $tabledb where defaultuser = '$newdefaultuser';"`
		if [ "$checkdefaultuser" == "$newdefaultuser" ]; then
			echo -en "$txtred""Callnumber $txtyellow$newdefaultuser$txtred already exists, please enter another:""$txtnormal"
		else
			# check that input data is a digital
			if [[ $newdefaultuser =~ $onlynumbers ]] ; then
				[ "4" -eq `echo -n $newdefaultuser | wc -m` ] && \
				$mysqlconnect -e "UPDATE $tabledb SET defaultuser = '$newdefaultuser' WHERE defaultuser = '$sipdefaultuser';" && \
				sipdefaultuser=$newdefaultuser && \
				break || \
				echo -en "$txtred""Callnumber must have 4 digitals only, please enter another: ""$txtnormal"
			else
				echo -en "$txtred""Callnumber must be numeric only, please enter another: ""$txtnormal"
			fi
		fi
	done
	# old context as default
	oldcontext=`$mysqlconnect -B -N -e "SELECT context FROM $tabledb WHERE defaultuser = '$sipdefaultuser';"`
	echo -n "New group(context)[$oldcontext]: "
	read newcontext
	[ -z "$newcontext" ] || $mysqlconnect -e "UPDATE $tabledb SET context = '$newcontext' WHERE defaultuser = '$sipdefaultuser';"
	# old name as default
	oldname=`$mysqlconnect -B -N -e "SELECT name FROM $tabledb WHERE defaultuser = '$sipdefaultuser';"`
	echo -n "New name[$oldname]: "
	while read newname ; do
	[ -z "$newname" ] && break
		checkname=`$mysqlconnect -B -N -e "select name from $tabledb where name = '$newname';"`
		if [ "$checkname" == "$newname" ]; then
			echo -en "$txtred""Name $txtyellow$newname$txtred already exists, please enter another: ""$txtnormal"
		else
			$mysqlconnect -e "UPDATE $tabledb SET name = '$newname' WHERE defaultuser = '$sipdefaultuser';"
			break
		fi
	done
	# old secret as default
	oldsecret=`$mysqlconnect -B -N -e "SELECT secret FROM $tabledb WHERE defaultuser = '$sipdefaultuser';"`
	echo -n "New password(secret)[$oldsecret]: "
	read newsecret
	[ -z "$newsecret" ] || $mysqlconnect -e "UPDATE $tabledb SET secret = '$newsecret' WHERE defaultuser = '$sipdefaultuser';"
	echo "Done."
	;;
    *)
	echo "Show as default for unusable action"
	$mysqlconnect -e "SELECT defaultuser,secret,context,name FROM $tabledb;"
        ;;
esac
done

exit 0
